ART_20_600: # SigType_LatDim_CompSize
  LatDim: 20 # The dimensionality of the latent variable z.
  SigType: rawART # Types of signals to train on.: ART, PLETH, II. 
  CompSize: 600 # Signal compression length (unit 0.01 second) "The value should be one of 100, 200, 300, 400, 500, 600, 700, 800"
  MaskingRate: 0.00 # The sequence masking ratio refers to the proportion of the sequence that will be masked during training.
  NoiseStd: 0.00 # The standard deviation value for Gaussian noise generation across the entire signal.
  MaskStd: 0.00 # The standard deviation value for Gaussian noise generation applied to the masked signal.
  ReparaStd: 0.1 # The standard deviation value for Gaussian noise generation used in the reparametrization trick.
  Capacity_Z: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of Z.
  Capacity_Fc: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of Fc.
  FcLimit: 0.05 # The upper threshold value for frequency.
  DecayH: 0.00 # The decay effect on the cutoff frequency when creating a high-pass filter.
  DecayL: 0.00 # The decay effect on the cutoff frequency when creating a low-pass filter.
  
  Patience: 300 # The patience value for early stopping during model training.
  
  WRec: 200 # The scaling weight for the reconstruction loss.
  WFeat: 400 # The scaling weight for the feature loss.
  WZ: 0.1 # The scaling weight for the Z loss.
  WFC: 0.1 # The scaling weight for the FC loss.
  WTC: 0.1 # The scaling weight for the TC loss.
  WMI: 0.1 # The scaling weight for the MI loss.
  
  MnWRec: 1 # The min weight for the reconstruction loss.
  MnWFeat: 1 # The min weight for the feature loss.
  MnWZ: 0.01 # The min weight for the Z loss.
  MnWFC: 0.01 # The min weight for the FC loss.
  MnWTC: 0.01 # The min weight for the TC loss.
  MnWMI: 0.01 # The min weight for the MI loss.
  
  MxWRec: 500 # The max weight for the reconstruction loss.
  MxWFeat: 500 # The max weight for the feature loss.
  MxWZ: 0.4 # The max weight for the Z loss.
  MxWFC: 0.25 # The max weight for the FC loss.
  MxWTC: 0.25 # The max weight for the TC loss.
  MxWMI: 0.25 # The max weight for the MI loss.
  
  
  
  
ART_30_700: # SigType_LatDim_CompSize
  LatDim: 30 # The dimensionality of the latent variable z.
  SigType: rawART # Types of signals to train on.: ART, PLETH, II. 
  CompSize: 700 # Signal compression length (unit 0.01 second) "The value should be one of 100, 200, 300, 400, 500, 600, 700, 800"
  MaskingRate: 0.00 # The sequence masking ratio refers to the proportion of the sequence that will be masked during training.
  NoiseStd: 0.00 # The standard deviation value for Gaussian noise generation across the entire signal.
  MaskStd: 0.00 # The standard deviation value for Gaussian noise generation applied to the masked signal.
  ReparaStd: 0.1 # The standard deviation value for Gaussian noise generation used in the reparametrization trick.
  Capacity_Z: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of Z.
  Capacity_Fc: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of Fc.
  FcLimit: 0.05 # The upper threshold value for frequency.
  DecayH: 0.00 # The decay effect on the cutoff frequency when creating a high-pass filter.
  DecayL: 0.00 # The decay effect on the cutoff frequency when creating a low-pass filter.
  
  Patience: 300 # The patience value for early stopping during model training.
  
  WRec: 300 # The scaling weight for the reconstruction loss.
  WFeat: 400 # The scaling weight for the feature loss.
  WZ: 0.1 # The scaling weight for the Z loss.
  WFC: 0.1 # The scaling weight for the FC loss.
  WTC: 0.1 # The scaling weight for the TC loss.
  WMI: 0.1 # The scaling weight for the MI loss.
  
  MnWRec: 1 # The min weight for the reconstruction loss.
  MnWFeat: 1 # The min weight for the feature loss.
  MnWZ: 0.05 # The min weight for the Z loss.
  MnWFC: 0.1 # The min weight for the FC loss.
  MnWTC: 0.01 # The min weight for the TC loss.
  MnWMI: 0.01 # The min weight for the MI loss.
  
  MxWRec: 800 # The max weight for the reconstruction loss.
  MxWFeat: 800 # The max weight for the feature loss.
  MxWZ: 0.45 # The max weight for the Z loss.
  MxWFC: 0.65 # The max weight for the FC loss.
  MxWTC: 0.25 # The max weight for the TC loss.
  MxWMI: 0.25 # The max weight for the MI loss.



TCL_ART_30_700: # SigType_LatDim_CompSize
  LatDim: 30 # The dimensionality of the latent variable z.
  SigType: rawART # Types of signals to train on.: ART, PLETH, II. 
  CompSize: 700 # Signal compression length (unit 0.01 second) "The value should be one of 100, 200, 300, 400, 500, 600, 700, 800"
  MaskingRate: 0.00 # The sequence masking ratio refers to the proportion of the sequence that will be masked during training.
  NoiseStd: 0.00 # The standard deviation value for Gaussian noise generation across the entire signal.
  MaskStd: 0.00 # The standard deviation value for Gaussian noise generation applied to the masked signal.
  ReparaStd: 0.1 # The standard deviation value for Gaussian noise generation used in the reparametrization trick.
  Capacity_Z: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of Z.
  Capacity_Fc: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of Fc.
  FcLimit: 0.05 # The upper threshold value for frequency.
  DecayH: 0.00 # The decay effect on the cutoff frequency when creating a high-pass filter.
  DecayL: 0.00 # The decay effect on the cutoff frequency when creating a low-pass filter.
  
  Patience: 300 # The patience value for early stopping during model training.
  
  WRec: 300 # The scaling weight for the reconstruction loss.
  WFeat: 400 # The scaling weight for the feature loss.
  WZ: 0.1 # The scaling weight for the Z loss.
  WFC: 0.1 # The scaling weight for the FC loss.
  WTC: 0.1 # The scaling weight for the TC loss.
  
  MnWRec: 1 # The min weight for the reconstruction loss.
  MnWFeat: 1 # The min weight for the feature loss.
  MnWZ: 0.05 # The min weight for the Z loss.
  MnWFC: 0.05 # The min weight for the FC loss.
  MnWTC: 0.01 # The min weight for the TC loss.
  
  MxWRec: 800 # The max weight for the reconstruction loss.
  MxWFeat: 800 # The max weight for the feature loss.
  MxWZ: 0.45 # The max weight for the Z loss.
  MxWFC: 0.55 # The max weight for the FC loss.
  MxWTC: 0.25 # The max weight for the TC loss.




