TCVAE_II_30: # SigType_LatDim
  LatDim: 30 # The dimensionality of the latent variable z.
  SigType: rawII # Types of signals to train on.: ART, PLETH, II. 
  ReparaStd: 0.1 # The standard deviation value for Gaussian noise generation used in the reparametrization trick.
  Capacity_Z: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of Z.
  Capacity_TC: 0.01 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of TC.
  Capacity_MI: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of MI.
  
  BatSize: 2800 # The batch size for the training
  NEpochs: 5000 # The epoch size for the training
    
  WRec: 1 # The scaling weight for the reconstruction loss.
  WZ: 1 # The scaling weight for the Z loss.
  WTC: 1 # The scaling weight for the TC loss.
  WMI: 1 # The scaling weight for the MI loss.
  
  MnWRec: 50 # The min weight for the reconstruction loss.
  MnWZ: 0.003 # The min weight for the Z loss.
  MnWTC: 0.0005 # The min weight for the TC loss. 
  MnWMI: 0.0005 # The min weight for the MI loss.
  
  MxWRec: 50 # The max weight for the reconstruction loss.
  MxWZ: 0.003 # The max weight for the Z loss.
  MxWTC: 0.0005 # The max weight for the TC loss.
  MxWMI: 0.0005 # The max weight for the MI loss.  
  

TCVAE_II_50: # SigType_LatDim
  LatDim: 50 # The dimensionality of the latent variable z.
  SigType: rawII # Types of signals to train on.: ART, PLETH, II. 
  ReparaStd: 0.1 # The standard deviation value for Gaussian noise generation used in the reparametrization trick.
  Capacity_Z: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of Z.
  Capacity_TC: 0.01 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of TC.
  Capacity_MI: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of MI.
  
  BatSize: 2800 # The batch size for the training
  NEpochs: 5000 # The epoch size for the training
  
  WRec: 1 # The scaling weight for the reconstruction loss.
  WZ: 1 # The scaling weight for the Z loss.
  WTC: 1 # The scaling weight for the TC loss.
  WMI: 1 # The scaling weight for the MI loss.
  
  MnWRec: 50 # The min weight for the reconstruction loss.
  MnWZ: 0.0005 # The min weight for the Z loss.
  MnWTC: 0.0001 # The min weight for the TC loss. 
  MnWMI: 0.0001 # The min weight for the MI loss.
  
  MxWRec: 50 # The max weight for the reconstruction loss.
  MxWZ: 0.0005 # The max weight for the Z loss.
  MxWTC: 0.0001 # The max weight for the TC loss.
  MxWMI: 0.0001 # The max weight for the MI loss.  


FACVAE_II_30: # SigType_LatDim
  LatDim: 30 # The dimensionality of the latent variable z.
  SigType: rawII # Types of signals to train on.: ART, PLETH, II. 
  DiscHiddenSize: 50 # The size of the hidden nodes within the discriminator model.
  ReparaStd: 0.1 # The standard deviation value for Gaussian noise generation used in the reparametrization trick.
  Capacity_Z: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of Z.
  Capacity_TC: 0.01 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of TC.
  Capacity_DTC: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of DTC.
  
  BatSize: 2800 # The batch size for the training
  NEpochs: 5000 # The epoch size for the training
  
  WRec: 1 # The scaling weight for the reconstruction loss.
  WZ: 1 # The scaling weight for the Z loss.
  WTC: 1 # The scaling weight for the TC loss.
  WDTC: 1 # The scaling weight for the DTC loss.
  
  MnWRec: 50 # The min weight for the reconstruction loss.
  MnWZ: 0.003 # The min weight for the Z loss.
  MnWTC: 0.001 # The min weight for the TC loss.
  MnWDTC: 0.001 # The min weight for the DTC loss.
  
  MxWRec: 50 # The max weight for the reconstruction loss.
  MxWZ: 0.003 # The max weight for the Z loss.
  MxWTC: 0.001 # The max weight for the TC loss.
  MxWDTC: 0.001 # The max weight for the DTC loss.  


FACVAE_II_50: # SigType_LatDim
  LatDim: 50 # The dimensionality of the latent variable z.
  SigType: rawII # Types of signals to train on.: ART, PLETH, II. 
  DiscHiddenSize: 50 # The size of the hidden nodes within the discriminator model.
  ReparaStd: 0.1 # The standard deviation value for Gaussian noise generation used in the reparametrization trick.
  Capacity_Z: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of Z.
  Capacity_TC: 0.01 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of TC.
  Capacity_DTC: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of DTC.
  
  BatSize: 2800 # The batch size for the training
  NEpochs: 5000 # The epoch size for the training
  
  WRec: 1 # The scaling weight for the reconstruction loss.
  WZ: 1 # The scaling weight for the Z loss.
  WTC: 1 # The scaling weight for the TC loss.
  WDTC: 1 # The scaling weight for the DTC loss.
  
  MnWRec: 50 # The min weight for the reconstruction loss.
  MnWZ: 0.003 # The min weight for the Z loss.
  MnWTC: 0.001 # The min weight for the TC loss.
  MnWDTC: 0.001 # The min weight for the DTC loss.
  
  MxWRec: 50 # The max weight for the reconstruction loss.
  MxWZ: 0.003 # The max weight for the Z loss.
  MxWTC: 0.001 # The max weight for the TC loss.
  MxWDTC: 0.001 # The max weight for the DTC loss.  
  

ConVAE_II_30: # SigType_LatDim
  LatDim: 30 # The dimensionality of the latent variable z.
  SigType: rawII # Types of signals to train on.: ART, PLETH, II. 
  ReparaStd: 0.1 # The standard deviation value for Gaussian noise generation used in the reparametrization trick.
  Capacity_Z: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of Z.

  BatSize: 2700 # The batch size for the training
  NEpochs: 5000 # The epoch size for the training
  
  WRec: 1 # The scaling weight for the reconstruction loss.
  WZ: 1 # The scaling weight for the Z loss.
  MnWRec: 50 # The min weight for the reconstruction loss.
  MnWZ: 0.003 # The min weight for the Z loss.
  MxWRec: 50 # The max weight for the reconstruction loss.
  MxWZ: 0.003 # The max weight for the Z loss.
  

ConVAE_II_50: # SigType_LatDim
  LatDim: 50 # The dimensionality of the latent variable z.
  SigType: rawII # Types of signals to train on.: ART, PLETH, II. 
  ReparaStd: 0.1 # The standard deviation value for Gaussian noise generation used in the reparametrization trick.
  Capacity_Z: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of Z.

  BatSize: 2700 # The batch size for the training
  NEpochs: 5000 # The epoch size for the training
  
  WRec: 1 # The scaling weight for the reconstruction loss.
  WZ: 1 # The scaling weight for the Z loss.
  MnWRec: 50 # The min weight for the reconstruction loss.
  MnWZ: 0.003 # The min weight for the Z loss.
  MxWRec: 50 # The max weight for the reconstruction loss.
  MxWZ: 0.003 # The max weight for the Z loss.
  
  
BaseVAE_II_50: # SigType_LatDim
  LatDim: 50 # The dimensionality of the latent variable z.
  SigType: rawII # Types of signals to train on.: ART, PLETH, II. 
  ReparaStd: 0.1 # The standard deviation value for Gaussian noise generation used in the reparametrization trick.
  Capacity_Z: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of Z.

  BatSize: 2800 # The batch size for the training
  NEpochs: 5000 # The epoch size for the training
  
  WRec: 1 # The scaling weight for the reconstruction loss.
  WZ: 1 # The scaling weight for the Z loss.
  MnWRec: 50 # The min weight for the reconstruction loss.
  MnWZ: 0.003 # The min weight for the Z loss.
  MxWRec: 50 # The max weight for the reconstruction loss.
  MxWZ: 0.003 # The max weight for the Z loss.
  
  
BaseVAE_II_30: # SigType_LatDim
  LatDim: 30 # The dimensionality of the latent variable z.
  SigType: rawII # Types of signals to train on.: ART, PLETH, II. 
  ReparaStd: 0.1 # The standard deviation value for Gaussian noise generation used in the reparametrization trick.
  Capacity_Z: 0.1 # The capacity value for controlling the Kullback-Leibler divergence (KLD) of Z.

  BatSize: 2800 # The batch size for the training
  NEpochs: 5000 # The epoch size for the training
  
  WRec: 1 # The scaling weight for the reconstruction loss.
  WZ: 1 # The scaling weight for the Z loss.
  MnWRec: 50 # The min weight for the reconstruction loss.
  MnWZ: 0.003 # The min weight for the Z loss.
  MxWRec: 50 # The max weight for the reconstruction loss.
  MxWZ: 0.003 # The max weight for the Z loss.
  